name: Build & Test
on: push

jobs:
  scalafmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SBT & ivy cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2
            ~/.sbt
            ~/.m2
            ~/.cache/coursier/
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - uses: sbt/setup-sbt@v1
      - name: Scalafmt
        run: sbt scalafmtCheckAll

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SBT & ivy cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2
            ~/.sbt
            ~/.m2
            ~/.cache/coursier/
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - uses: sbt/setup-sbt@v1
      - name: Compile
        run: sbt +compile

  test:
    name: Test Samples
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Cache SBT & ivy cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2
            ~/.sbt
            ~/.m2
            ~/.cache/coursier/
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - uses: sbt/setup-sbt@v1
      - name: Test Samples
        run: sbt +samples/it:test

  scapegoat:
    name: Scapegoat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SBT & ivy cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2
            ~/.sbt
            ~/.m2
            ~/.cache/coursier/
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - uses: sbt/setup-sbt@v1
      - name: Run scapegoat
        run: sbt scapegoat

  mima:
    name: Report Binary Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache SBT & ivy cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2
            ~/.sbt
            ~/.m2
            ~/.cache/coursier/
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/plugins.sbt') }}-${{ hashFiles('**/build.properties') }}
      - uses: sbt/setup-sbt@v1
      - name: Run mima
        run: sbt mimaReportBinaryIssues
